public class MultipleCatchBlock5
{
    public static void main(String[]args)
    {
        try
        {
            int arr[]= new int[5];
            arr[5]=50/0;
        }
        catch(Exception e)
        {
            System.out.println("Parent exception occur");
        }
        catch(ArithmeticException e)
        {
            System.out.println("Arithmetic Exception occur");
        }
        catch(ArrayIndexOutOfBoundsException e)
        {
            System.out.println("Array index out of bouunds exception occur");
        }
        System.out.println("Rest of the code");
    }
}
